/**
 * Generates the illustration library from `illustrations/<profile>/<name>/`.
 *
 * Each profile folder has a `colors.json` (the palette used by its
 * illustrations, with light and dark values) and one folder per illustration
 * containing exactly one `.svg` file and a `meta.json` (see `meta.schema.json`).
 *
 * For every profile this writes, under `generated/illustrations/<profile>/`:
 *   - `react/<Name>.tsx` + `react/index.ts`  React components
 *   - `svg.ts`                                framework-agnostic SVG strings
 *   - `meta.ts`                               titles, tags, colours, slots
 * and, under `dist/illustrations/`, a `<profile>.css` with the colour
 * variables plus an `index.css` combining every profile. The shared types and
 * helpers in `src/illustrations/index.ts` are copied to
 * `generated/illustrations/index.ts` with the profile list and loaders added.
 *
 * Colours: hard-coded palette colours are replaced with
 * `var(--varde-illustration-<profile>-<colour>, <light hex>)`, so the SVGs
 * render correctly without the CSS and switch to the dark palette when the
 * CSS is loaded and `data-color-scheme="dark"` is set.
 *
 * Colour slots: a layer named `Former [brand1,brand2]` in Illustrator marks
 * the shape(s) as recolourable to the listed palette colours. The build reads
 * the marker from the exported `data-name` attribute (Illustrator flattens the
 * brackets in `id`), gives the slot its own variable that falls back to the
 * drawn colour, adds a typed prop to the React component and lists the slot
 * in `meta.ts`. Layers without a `[...]` list are never recoloured.
 *
 * Run with `node scripts/build-illustrations.ts` (Node ≥ 22.18 strips types),
 * then compile `generated/` with `tsc -p tsconfig.build.json`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';
import { type CustomPlugin, optimize, type XastElement } from 'svgo';
import type {
  IllustrationColor,
  IllustrationMeta,
  IllustrationSlot,
} from '../src/illustrations/index.ts';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const sourceDir = path.join(packageRoot, 'illustrations');
const runtimeSource = path.join(
  packageRoot,
  'src',
  'illustrations',
  'index.ts',
);
const generatedDir = path.join(packageRoot, 'generated', 'illustrations');
const distDir = path.join(packageRoot, 'dist', 'illustrations');

const VARIABLE_PREFIX = '--varde-illustration';
const GENERATED_HEADER =
  '// Generated by scripts/build-illustrations.ts – do not edit.';

type ColorDefinition = { label?: string; light: string; dark: string };
type Palette = Record<string, ColorDefinition>;

type Meta = {
  $schema?: string;
  title: string;
  description?: string;
  tags: string[];
};

type Illustration = IllustrationMeta & { svg: string };

const SLUG_PATTERN = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
const HEX_COLOR = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i;
const ANY_HEX_COLOR = /#(?:[0-9a-f]{3}|[0-9a-f]{6})\b/gi;
const COLOR_ATTRIBUTES = [
  'fill',
  'stroke',
  'stop-color',
  'flood-color',
  'lighting-color',
];
/** Keep full, lower-case-insensitive hex values so palette lookups are exact. */
const CONVERT_COLORS = {
  currentColor: false,
  names2hex: true,
  rgb2hex: true,
  shorthex: false,
  shortname: false,
};
/** Props already used by the generated component, so slots can't take them. */
const RESERVED_PROPS = new Set([
  'title',
  'titleId',
  'style',
  'ref',
  'key',
  'children',
]);

const toPascalCase = (slug: string) =>
  slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const toCamelCase = (slug: string) => {
  const pascal = toPascalCase(slug);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

/** "Former og figurer" → "former-og-figurer" (æøå folded to ASCII). */
const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/æ/g, 'ae')
    .replace(/ø/g, 'o')
    .replace(/å/g, 'a')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const readJson = <T>(file: string): T =>
  JSON.parse(fs.readFileSync(file, 'utf8')) as T;

const listDirectories = (dir: string) =>
  fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

/** Expand `#abc` to `#aabbcc` and lower-case, so palette lookups are stable. */
const normalizeHex = (hex: string) => {
  const value = hex.toLowerCase();
  if (value.length === 4) {
    return `#${value[1]}${value[1]}${value[2]}${value[2]}${value[3]}${value[3]}`;
  }
  return value;
};

const readPalette = (profile: string): IllustrationColor[] => {
  const file = path.join(sourceDir, profile, 'colors.json');
  if (!fs.existsSync(file)) {
    throw new Error(`Missing ${path.relative(packageRoot, file)}`);
  }

  const palette = readJson<Palette>(file);

  return Object.entries(palette).map(([name, definition]) => {
    if (!SLUG_PATTERN.test(name)) {
      throw new Error(
        `Colour "${name}" in ${profile}/colors.json must be kebab-case (a-z, 0-9, -).`,
      );
    }
    for (const mode of ['light', 'dark'] as const) {
      if (!/^#[0-9a-f]{6}$/i.test(definition?.[mode] ?? '')) {
        throw new Error(
          `Colour "${name}" in ${profile}/colors.json needs a 6-digit hex "${mode}" value.`,
        );
      }
    }
    return {
      name,
      label: definition.label ?? name,
      variable: `${VARIABLE_PREFIX}-${profile}-${name}`,
      light: normalizeHex(definition.light),
      dark: normalizeHex(definition.dark),
    };
  });
};

const readMeta = (dir: string): Meta => {
  const file = path.join(dir, 'meta.json');
  if (!fs.existsSync(file)) {
    throw new Error(`Missing ${path.relative(packageRoot, file)}`);
  }

  const meta = readJson<Meta>(file);
  const relative = path.relative(packageRoot, file);

  if (typeof meta.title !== 'string' || meta.title.trim() === '') {
    throw new Error(`${relative}: "title" must be a non-empty string.`);
  }
  if (
    !Array.isArray(meta.tags) ||
    meta.tags.some((tag) => typeof tag !== 'string' || tag.trim() === '')
  ) {
    throw new Error(`${relative}: "tags" must be an array of strings.`);
  }
  if (meta.description !== undefined && typeof meta.description !== 'string') {
    throw new Error(`${relative}: "description" must be a string.`);
  }

  return meta;
};

const findSvgFile = (dir: string) => {
  const svgs = fs.readdirSync(dir).filter((file) => file.endsWith('.svg'));
  const relative = path.relative(packageRoot, dir);

  if (svgs.length === 0) {
    throw new Error(`${relative}: no .svg file found.`);
  }
  if (svgs.length > 1) {
    throw new Error(
      `${relative}: expected exactly one .svg file, found ${svgs.join(', ')}.`,
    );
  }
  return path.join(dir, svgs[0]);
};

// ---------------------------------------------------------------------------
// Colours and slots
// ---------------------------------------------------------------------------

const SLOT_MARKER = /^(.*?)\s*\[([^\]]*)\]\s*$/;

/** Parse `Former [brand1,brand2]` → { label: 'Former', colors: [...] }. */
const parseSlotMarker = (
  layerName: string,
  colors: IllustrationColor[],
  context: string,
) => {
  const match = layerName.match(SLOT_MARKER);
  if (!match) return null;

  const label = match[1].trim();
  const list = match[2]
    .split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);

  if (!label) {
    throw new Error(
      `${context}: layer "${layerName}" has no name before [...].`,
    );
  }
  if (list.length === 0) {
    throw new Error(
      `${context}: layer "${layerName}" has an empty colour list. Remove the brackets to keep the colour fixed.`,
    );
  }
  const known = new Set(colors.map((color) => color.name));
  for (const color of list) {
    if (!known.has(color)) {
      throw new Error(
        `${context}: layer "${layerName}" lists unknown colour "${color}". Use one of: ${[...known].join(', ')}.`,
      );
    }
  }
  return { label, colors: [...new Set(list)] };
};

/**
 * Register the slot for a layer marked `Name [colour,…]`, or return undefined
 * for ordinary layers. Layers sharing a name share one slot.
 */
const registerSlot = (
  layerName: string,
  slots: Map<string, IllustrationSlot>,
  colors: IllustrationColor[],
  profile: string,
  name: string,
) => {
  const context = `${profile}/${name}`;
  const marker = parseSlotMarker(layerName, colors, context);
  if (!marker) return undefined;

  const slotName = slugify(marker.label);
  if (!SLUG_PATTERN.test(slotName)) {
    throw new Error(
      `${context}: layer "${layerName}" needs a name starting with a letter.`,
    );
  }
  const prop = toCamelCase(slotName);
  if (RESERVED_PROPS.has(prop)) {
    throw new Error(
      `${context}: layer name "${marker.label}" clashes with the "${prop}" prop – pick another name.`,
    );
  }

  const existing = slots.get(slotName);
  if (existing) {
    if (existing.colors.join() !== marker.colors.join()) {
      throw new Error(
        `${context}: layers named "${marker.label}" list different colours. Layers with the same name share one slot and must agree.`,
      );
    }
    return existing;
  }

  const slot: IllustrationSlot = {
    name: slotName,
    label: marker.label,
    prop,
    variable: `${VARIABLE_PREFIX}-${profile}-${name}-${slotName}`,
    default: '',
    colors: marker.colors,
  };
  slots.set(slotName, slot);
  return slot;
};

/**
 * svgo plugin that swaps palette colours for CSS variables and registers
 * colour slots from `data-name` markers. Inside a slotted element, shapes
 * drawn in the slot's colour get the slot variable (falling back to the
 * palette variable); everything else gets the palette variable.
 */
const themeColorsPlugin = (
  byHex: Map<string, IllustrationColor>,
  colors: IllustrationColor[],
  slots: Map<string, IllustrationSlot>,
  profile: string,
  name: string,
): CustomPlugin => ({
  name: 'vardeThemeColors',
  fn: () => {
    const stack: { node: XastElement; slot: IllustrationSlot }[] = [];

    return {
      element: {
        enter: (node: XastElement) => {
          const layerName = node.attributes['data-name'];
          const slot =
            layerName && registerSlot(layerName, slots, colors, profile, name);
          if (slot) stack.push({ node, slot });
          const active = stack.at(-1)?.slot;

          for (const attribute of COLOR_ATTRIBUTES) {
            const value = node.attributes[attribute];
            if (!value || !HEX_COLOR.test(value)) continue;
            const color = byHex.get(normalizeHex(value));
            if (!color) continue; // reported after optimisation
            const paletteVar = `var(${color.variable}, ${color.light})`;

            // The first palette colour met inside a slot (the marked element
            // itself comes first) is the colour that slot swaps.
            if (active && !active.default) active.default = color.name;

            node.attributes[attribute] =
              active && active.default === color.name
                ? `var(${active.variable}, ${paletteVar})`
                : paletteVar;
          }
        },
        exit: (node: XastElement) => {
          if (stack.at(-1)?.node === node) stack.pop();
        },
      },
    };
  },
});

/**
 * Optimise the SVG and swap palette colours for CSS variables. Any colour that
 * is not in the palette is left as-is and reported, so it can be added to
 * `colors.json` (or fixed in the SVG).
 */
const processSvg = (
  svg: string,
  profile: string,
  name: string,
  colors: IllustrationColor[],
) => {
  const context = `${profile}/${name}`;
  const byHex = new Map(colors.map((color) => [color.light, color]));
  const slots = new Map<string, IllustrationSlot>();

  // Pass 1: get every colour onto an attribute and swap it for a variable,
  // before preset-default merges paths, hoists attributes or drops data-name.
  const themed = optimize(svg, {
    multipass: false,
    plugins: [
      'mergeStyles',
      { name: 'inlineStyles', params: { onlyMatchedOnce: false } },
      'convertStyleToAttrs',
      { name: 'convertColors', params: CONVERT_COLORS },
      themeColorsPlugin(byHex, colors, slots, profile, name),
    ],
  }).data;

  // Pass 2: the usual optimisation.
  const optimized = optimize(themed, {
    multipass: true,
    plugins: [
      {
        name: 'preset-default',
        params: { overrides: { convertColors: CONVERT_COLORS } },
      },
      // Several illustrations may be inlined on one page – keep ids unique.
      { name: 'prefixIds', params: { prefix: name } },
      // Drop the root width/height so the container decides the size, and
      // Illustrator's data-name attributes (the viewBox is kept – svgo 4 no
      // longer removes it by default).
      {
        name: 'removeAttrs',
        params: { attrs: ['svg:(width|height)', 'data-name'] },
      },
    ],
  }).data;

  // Anything still hard-coded was not in the palette (or sat in a style).
  const unknown = new Set(
    (optimized.match(ANY_HEX_COLOR) ?? []).filter(
      (hex) => !byHex.has(normalizeHex(hex)),
    ),
  );
  if (unknown.size > 0) {
    console.warn(
      `  ⚠ ${context}: colour(s) ${[...unknown].join(', ')} are not in ${profile}/colors.json and will not follow the colour scheme.`,
    );
  }

  for (const slot of slots.values()) {
    if (!slot.default) {
      throw new Error(
        `${context}: layer "${slot.label}" is marked as a colour slot but no palette colour was found in it.`,
      );
    }
    if (!slot.colors.includes(slot.default)) {
      console.warn(
        `  ⚠ ${context}: layer "${slot.label}" is drawn in "${slot.default}" but does not list it – adding it.`,
      );
      slot.colors.unshift(slot.default);
    }
  }

  return { svg: optimized, slots: [...slots.values()] };
};

// ---------------------------------------------------------------------------
// React components
// ---------------------------------------------------------------------------

/**
 * SVGR renders only an inner `Svg` function (props + ref, no export); the
 * exported component is written by us below, so slot props never depend on
 * SVGR's output formatting.
 */
const buildReactComponent = async (
  svg: string,
  componentName: string,
  profile: string,
  slots: IllustrationSlot[],
) => {
  const inner = await transform(
    svg,
    {
      plugins: ['@svgr/plugin-jsx'],
      typescript: true,
      jsxRuntime: 'automatic',
      ref: true,
      titleProp: true,
      dimensions: false,
      expandProps: 'end',
      template: (variables, { tpl }) => tpl`
        ${variables.imports};
        ${variables.interfaces};
        const ${variables.componentName} = (${variables.props}) => (
          ${variables.jsx}
        );
      `,
    },
    { componentName: 'Svg' },
  );

  if (slots.length === 0) {
    return [
      GENERATED_HEADER,
      inner,
      `const ${componentName} = forwardRef(Svg);`,
      `export default ${componentName};`,
      '',
    ].join('\n');
  }

  const slotProps = slots
    .map(
      (slot) =>
        `  /** Colour of "${slot.label}". Defaults to "${slot.default}". */\n  ${slot.prop}?: ${slot.colors.map((color) => `'${color}'`).join(' | ')};`,
    )
    .join('\n');
  const slotVariables = slots
    .map((slot) => `'${slot.variable}': ${slot.prop}`)
    .join(', ');
  const destructured = slots.map((slot) => slot.prop).join(', ');

  return [
    GENERATED_HEADER,
    "import { applySlots } from '../../index.js';",
    inner,
    'interface SlotProps {',
    slotProps,
    '}',
    `const ${componentName} = forwardRef<SVGSVGElement, Parameters<typeof Svg>[0] & SlotProps>(`,
    `  ({ ${destructured}, style, ...props }, ref) =>`,
    `    Svg({ ...props, style: applySlots(style, '${VARIABLE_PREFIX}-${profile}', { ${slotVariables} }) }, ref),`,
    ');',
    `export default ${componentName};`,
    '',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

const buildProfile = async (profile: string) => {
  const profileDir = path.join(sourceDir, profile);
  const outDir = path.join(generatedDir, profile);
  const reactDir = path.join(outDir, 'react');
  fs.mkdirSync(reactDir, { recursive: true });

  const colors = readPalette(profile);
  const illustrations: Illustration[] = [];

  for (const name of listDirectories(profileDir)) {
    if (!SLUG_PATTERN.test(name)) {
      throw new Error(
        `Illustration folder "${profile}/${name}" must be kebab-case (a-z, 0-9, -) and start with a letter.`,
      );
    }

    const dir = path.join(profileDir, name);
    const meta = readMeta(dir);
    const rawSvg = fs.readFileSync(findSvgFile(dir), 'utf8');
    const { svg, slots } = processSvg(rawSvg, profile, name, colors);
    const componentName = toPascalCase(name);

    fs.writeFileSync(
      path.join(reactDir, `${componentName}.tsx`),
      await buildReactComponent(svg, componentName, profile, slots),
    );

    illustrations.push({
      name,
      componentName,
      exportName: toCamelCase(name),
      title: meta.title,
      description: meta.description,
      tags: meta.tags,
      viewBox: svg.match(/viewBox=["']([^"']+)["']/)?.[1],
      slots,
      svg,
    });
  }

  if (illustrations.length === 0) {
    console.warn(`  ⚠ ${profile}: no illustrations found.`);
  }

  fs.writeFileSync(
    path.join(reactDir, 'index.ts'),
    [
      GENERATED_HEADER,
      ...illustrations.map(
        (item) =>
          `export { default as ${item.componentName} } from './${item.componentName}.js';`,
      ),
      '',
    ].join('\n'),
  );

  fs.writeFileSync(
    path.join(outDir, 'svg.ts'),
    [
      GENERATED_HEADER,
      '// Framework-agnostic SVG strings. Load `@digdir/varde/illustrations.css`',
      '// (or `@digdir/varde/illustrations/<profile>.css`) for dark mode support.',
      '',
      ...illustrations.map(
        (item) =>
          `export const ${item.exportName} = ${JSON.stringify(item.svg)};`,
      ),
      '',
    ].join('\n'),
  );

  const metaEntries = illustrations.map(({ svg: _svg, ...rest }) => rest);
  fs.writeFileSync(
    path.join(outDir, 'meta.ts'),
    [
      GENERATED_HEADER,
      "import type { IllustrationColor, IllustrationMeta } from '../index.js';",
      '',
      `export const profile = ${JSON.stringify(profile)};`,
      '',
      `export const colors: IllustrationColor[] = ${JSON.stringify(colors, null, 2)};`,
      '',
      `export const illustrations: IllustrationMeta[] = ${JSON.stringify(metaEntries, null, 2)};`,
      '',
    ].join('\n'),
  );

  const declarations = (mode: 'light' | 'dark') =>
    colors.map((color) => `  ${color.variable}: ${color[mode]};`).join('\n');
  const css = [
    `/* Generated by scripts/build-illustrations.ts – do not edit. */`,
    `/* Colours for the "${profile}" illustrations in @digdir/varde. */`,
    ':root,',
    `[data-color-scheme='light'] {`,
    declarations('light'),
    '}',
    '',
    `[data-color-scheme='dark'] {`,
    declarations('dark'),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    `  [data-color-scheme='auto'] {`,
    declarations('dark').replace(/^/gm, '  '),
    '  }',
    '}',
    '',
  ].join('\n');
  fs.writeFileSync(path.join(distDir, `${profile}.css`), css);

  const slotCount = illustrations.reduce(
    (sum, item) => sum + item.slots.length,
    0,
  );
  console.log(
    `  ✓ ${profile}: ${illustrations.length} illustration(s), ${slotCount} colour slot(s)`,
  );
  return css;
};

/** `@digdir/varde/illustrations`: the checked-in runtime plus generated data. */
const writeIndex = (profiles: string[]) => {
  const runtime = fs
    .readFileSync(runtimeSource, 'utf8')
    .replace(
      /^\/\*\*[\s\S]*?\*\/\n/,
      `${GENERATED_HEADER}\n// Source: src/illustrations/index.ts\n`,
    );

  const loaders = profiles.map(
    (profile) =>
      `  ${JSON.stringify(profile)}: () =>\n    loadIllustrationLibrary(import('./${profile}/meta.js'), import('./${profile}/svg.js')),`,
  );

  fs.writeFileSync(
    path.join(generatedDir, 'index.ts'),
    [
      runtime,
      '/** Profiles that ship illustrations. */',
      `export const illustrationProfiles = ${JSON.stringify(profiles)} as const;`,
      '',
      'export type IllustrationProfile = (typeof illustrationProfiles)[number];',
      '',
      '/**',
      " * Lazy loader per profile. Each loads that profile's metadata and SVG",
      ' * strings on demand, so bundlers can split them per profile.',
      ' */',
      'export const illustrationLoaders: Record<',
      '  IllustrationProfile,',
      '  () => Promise<IllustrationLibrary>',
      '> = {',
      ...loaders,
      '};',
      '',
    ].join('\n'),
  );
};

const build = async () => {
  fs.rmSync(generatedDir, { recursive: true, force: true });
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.mkdirSync(distDir, { recursive: true });

  const profiles = listDirectories(sourceDir);
  console.log(`Building illustrations for ${profiles.length} profile(s)…`);

  const cssChunks: string[] = [];
  for (const profile of profiles) {
    cssChunks.push(await buildProfile(profile));
  }
  fs.writeFileSync(path.join(distDir, 'index.css'), cssChunks.join('\n'));

  writeIndex(profiles);
};

build().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
